# Generated by Django 3.1.3 on 2020-11-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='checked',
            field=models.BooleanField(),
        ),
    ]
